name: clash_window_dll
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0-46.0.dev <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  utils:
    path: ../utils
flutter:

  plugin:
    platforms:
      windows:
        pluginClass: ClashWindowDllPlugin